# Language selection for the checker

language_options:
  - python

# Default language if not specified
default_language: python

# Checker configuration
checker:
  enabled: true
  strict_mode: false
  
# Output settings

